apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: globeco-portfolio-management-portal
  namespace: globeco
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: globeco.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: globeco-portfolio-management-portal
                port:
                  number: 3000 