apiVersion: v1
kind: Service
metadata:
  name: globeco-portfolio-management-portal-nodeport
  namespace: globeco
  labels:
    app: globeco-portfolio-management-portal
spec:
  type: NodePort
  selector:
    app: globeco-portfolio-management-portal
  ports:
    - port: 32080      # Internal cluster port
      targetPort: 3000 # Port your container app listens on
      nodePort: 32080  # Exact external port (Must be 30000-32767)
